# Generated by Django 3.0.8 on 2020-07-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdesc', models.TextField()),
                ('csme', models.IntegerField()),
                ('cparticipants', models.IntegerField()),
                ('cdesigners', models.IntegerField()),
                ('cdobegin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registerpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(null=True)),
                ('bname', models.CharField(max_length=40, null=True)),
                ('bemail', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('certificate', models.CharField(blank=True, max_length=40, null=True)),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('designer', models.CharField(max_length=40, null=True)),
                ('ratings', models.CharField(max_length=40, null=True)),
                ('quantity', models.CharField(max_length=40, null=True)),
                ('price', models.CharField(max_length=40, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('kids-boys', 'kids-boys'), ('kids-girls', 'kids-girls')], max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.CharField(max_length=40, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Registerpage')),
            ],
        ),
    ]
