# Generated by Django 3.0.7 on 2020-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
    ]
