# Generated by Django 3.0.7 on 2020-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designerprofile',
            old_name='name',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='designerprofile',
            old_name='phn',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='designerprofile',
            old_name='surname',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='additionaldetails',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='Mobile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
