# Generated by Django 3.0.7 on 2020-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_auto_20200718_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerprofile',
            name='About',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='state',
        ),
    ]
