# Generated by Django 3.0.8 on 2020-07-15 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('surname', models.CharField(blank=True, default='Surname', max_length=200, null=True)),
                ('phn', models.CharField(blank=True, default='Phone number', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='Email', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='Address', max_length=50, null=True)),
                ('education', models.CharField(blank=True, default='education', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='country', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='state', max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile2.png', null=True, upload_to='user/')),
                ('experience', models.CharField(blank=True, default='Experience', max_length=300, null=True)),
                ('additionaldetails', models.CharField(blank=True, default='Additional details', max_length=300, null=True)),
                ('sublist', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=105, size=5)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
